data:
  train:
    data_path: /data/path
    ann_path: /ann/path
  val:
    data_path: /data/path
    ann_path: /ann/path

model:
  name: "PekingU/rtdetr_r18vd"
  hyps:
    num_train_epochs: 10
    learning_rate: 0.0005
    lr_scheduler_type: linear
    warmup_steps: 300
    per_device_train_batch_size: 2
    gradient_accumulation_steps: 4
    eval_accumulation_steps: 2
    per_device_eval_batch_size: 2
    dataloader_num_workers: 2
    save_total_limit: 2
    eval_strategy: epoch
    save_strategy: epoch
    output_dir: /out/dir
    run_name: rtdetr_r18vd_train
  device: cuda:0
  
