name: Run FastApi Tests

on: 
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main 

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Set up AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Ensure you have this file in the specified directory
          pip install awscli
        working-directory: serving/gradio_server 

      - name: Run AWS S3 Copy Command
        run: |
          aws s3 cp s3://mlp-data-2024/rtdetr_model/ ./rtdetr_model --recursive
        working-directory: serving/gradio_server 

      - name: Run tests
        run: |
          python -m pytest tests  # This will run all tests in the specified directory
        working-directory: serving/gradio_server  
